[project]
name = "reconciler"
authors = [
    { name = "Aerele Technologies Private Limited", email = "admin@aerele.in"}
]
description = "Reconciliation tool for GSTR 2A and Purchase Invoice"
requires-python = ">=3.10"
readme = "README.md"
dynamic = ["version"]
dependencies = [
    # "frappe~=15.0.0" # Installed and managed by bench.
]

[build-system]
requires = ["flit_core >=3.4,<4"]
build-backend = "flit_core.buildapi"

[tool.bench.frappe-dependencies]
frappe = ">=16.0.0,<17.0.0"
erpnext = ">=16.0.0,<17.0.0"
